name: Testing

on:
  push:
    branches: [ "main", "solution" ]
  pull_request:
    branches: [ "main", "solution" ]
  schedule:
     - cron: "0 0 * * *"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      CC: clang-18
      CXX: clang++-18

    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Bench
      run: |
        ${{github.workspace}}/build/task1
        ${{github.workspace}}/build/task2

